apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems
  template:
    metadata:
      labels:
        app: ems
    spec:
      containers:
      - name: ems
        image: ems:latest
        ports:
        - containerPort: 8080